### ISSUE TITLE
sscanf("%hhu") destroys memory

### ISSUE THREAD

**Issue by matsujirushi** [Seeed-Studio/Wio_Tracker_1110_Examples#22]
sscanf("%hhu") writes 2 bytes.

Code:

```cpp
  static uint8_t data[4] = { 0x12, 0x34, 0x56, 0x78 };
  printf("%d\n", sscanf("154", "%hhu", &data[1]));
```

Output:
```
1
```

Memory:
![image](https://github.com/Seeed-Studio/Wio_Tracker_1110_Examples/assets/8079404/565776eb-8a3a-4197-993b-e7833641ff79)

# Reference

https://ja-support.renesas.com/knowledgeBase/20441082

**Comment by matsujirushi** [comment]
Used in 3 places.

![image](https://github.com/Seeed-Studio/Wio_Tracker_1110_Examples/assets/8079404/0a4172c6-5480-4d45-90f4-0f6aca4ecc85)

**Comment by ackPeng** [comment]
Thank you very much, could you please submit a PR to us?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
