### ISSUE TITLE
Request to add P2P example for connection between two Wio Tracker 1110

### ISSUE THREAD

**Issue by idreamsi** [Seeed-Studio/Wio_Tracker_1110_Examples#24]
One thing I didn't find in the examples section is ```P2P connection``` (point to point) without needing a LoRaWAN network.
Please put a arduino example of a P2P connection for communication between two Wio Tracker 1110 in this section, it seems that an example can be found [here](https://github.com/Lora-net/SWSD003/blob/master/lr11xx/apps/ping_pong/main_ping_pong.c).

Thanks.

**Comment by idreamsi** [comment]
[This example](https://github.com/Lora-net/SWSD001/tree/master/apps/examples/tx_rx_continuous) also seems to be a working example for TX/RX.

**Comment by KillingJacky** [comment]
Sorry for no replying such a long time. The p2p example is not planned though, as you pointed out, those are the existing examples that you could explore and get start from. Thanks for your understanding.
