### ISSUE TITLE
Firmware updater not compiling

### ISSUE THREAD

**Issue by cobraPA** [Seeed-Studio/Wio_Tracker_1110_Examples#25]
It seems the firmware updater does not compile in platformio,
there is a missing function for the dfu_bootload setup:

static int usrcmd_enter_bootloader_mode(int argc, char **argv)
{
    // not found
    wm1110Hw.enterBootloaderMode();

    return 0;
}

**Comment by cobraPA** [comment]
Compiling .pio\build\release\src\main.cpp.o
src\main.cpp: In function 'int usrcmd_enter_bootloader_mode(int, char**)':
src\main.cpp:224:14: error: 'class Wm1110Hardware' has no member named 'enterBootloaderMode'
     wm1110Hw.enterBootloaderMode();

**Comment by tve** [comment]
I believe it needs to call `lr11xx_bootloader_reboot` in the lr111x driver, now how to get there from here...

**Comment by wzy-github123** [comment]
commit [b939635](https://github.com/Seeed-Studio/Adafruit_nRF52_Arduino/commit/b939635e3a5b19dc79ede3d71034607932e2dc46) fixed it.

**Comment by KillingJacky** [comment]
fix in https://github.com/Seeed-Studio/Adafruit_nRF52_Arduino/commit/b939635e3a5b19dc79ede3d71034607932e2dc46
